---
- name: Converge
  hosts: all
  become: true
  gather_facts: false
  roles:
    - role: msterhuj.chrony
      chrony_acl:
        - allow 0/0
      chrony_enable_tracking_measurements_statistics: true
